In [ ]:
import pandas as pd

In [ ]:
# 데이터 불러오기
df = pd.read_csv('/content/drive/MyDrive/bgg-19m-reviews.csv')

In [ ]:
# 기본 데이터
df

,Unnamed: 0,user,rating,comment,ID,name
0,0,Torsten,10.0,NaN,30549,Pandemic
1,1,mitnachtKAUBO-I,10.0,Hands down my favorite new game of BGG CON 200...,30549,Pandemic
2,2,avlawn,10.0,I tend to either love or easily tire of co-op ...,30549,Pandemic
3,3,Mike Mayer,10.0,NaN,30549,Pandemic
4,4,Mease19,10.0,This is an amazing co-op game. I play mostly ...,30549,Pandemic
...,...,...,...,...,...,...
18964802,18964802,Ceryon,3.1,NaN,1752,Haps
18964803,18964803,Gregarius,2.0,"I hated this game. Too complicated to set up, ...",1752,Haps
18964804,18964804,Lajos,2.0,Sold in Geekauction for 3 GG.,1752,Haps
18964805,18964805,Imagine,1.0,This game is not for me - I just didn&#039;t g...,1752,Haps
18964806,18964806,gonzo104,1.0,NaN,1752,Haps

In [ ]:
# 불필요한 열 제거
df.drop(['Unnamed: 0','user'],axis = 1, inplace = True)
df

,rating,comment,ID,name
0,10.0,NaN,30549,Pandemic
1,10.0,Hands down my favorite new game of BGG CON 200...,30549,Pandemic
2,10.0,I tend to either love or easily tire of co-op ...,30549,Pandemic
3,10.0,NaN,30549,Pandemic
4,10.0,This is an amazing co-op game. I play mostly ...,30549,Pandemic
...,...,...,...,...
18964802,3.1,NaN,1752,Haps
18964803,2.0,"I hated this game. Too complicated to set up, ...",1752,Haps
18964804,2.0,Sold in Geekauction for 3 GG.,1752,Haps
18964805,1.0,This game is not for me - I just didn&#039;t g...,1752,Haps
18964806,1.0,NaN,1752,Haps

In [ ]:
# 결측치 확인
df.isnull().sum()

rating            0
comment    15596188
ID                0
name              0
dtype: int64

In [ ]:
# 리뷰(comment) 결측치 제거
df.dropna(inplace=True)
df

,rating,comment,ID,name
1,10.0,Hands down my favorite new game of BGG CON 200...,30549,Pandemic
2,10.0,I tend to either love or easily tire of co-op ...,30549,Pandemic
4,10.0,This is an amazing co-op game. I play mostly ...,30549,Pandemic
5,10.0,Hey! I can finally rate this game I've been pl...,30549,Pandemic
8,10.0,Love it- great fun with my son. 2 plays so far...,30549,Pandemic
...,...,...,...,...
18964798,4.0,"Sadly, to slow moving and fiddly!",1752,Haps
18964800,4.0,"Weird card game with some nice gameplay, but a...",1752,Haps
18964803,2.0,"I hated this game. Too complicated to set up, ...",1752,Haps
18964804,2.0,Sold in Geekauction for 3 GG.,1752,Haps
18964805,1.0,This game is not for me - I just didn&#039;t g...,1752,Haps

In [ ]:
# 리뷰 수에 따라 정렬
review_count = df.groupby(['ID']).size().reset_index(name='counts').sort_values('counts',ascending = False)
review_count

           ID  counts
672       822   16627
12         13   16567
7891    30549   14521
9825    68448   12341
8430    36218   11913
...       ...     ...
20501  291154       1
21511  325834       1
11200  116849       1
8221    33836       1
12196  138167       1

[21828 rows x 2 columns]

In [ ]:
# 대중성을 위해 리뷰 수가 1500개(최다 리뷰의 10% 정도) 이상인 게임 목록 추출
ID = review_count[review_count['counts']>1500]['ID'].unique()
ID

array([   822,     13,  30549,  68448,  36218,   9209,  31260,   3076,
         2651, 167791,  70323,  28143,    478,  40692, 178900,     50,
       129622, 169786,  14996, 173346, 148228,     11,  15987,  12333,
        39856,  65244,  34635,  10547, 174430, 110327,  84876,   1927,
       230802, 266192,    463,    181,  37111,   1406,    171,  10630,
        54043,     42,   6249,   2655,  98778, 161936, 163412, 131357,
          172,  18602,   3955,  31481,  41114,  15062, 147020, 120677,
         8217,    320,  39463, 150376,     18,  96848, 121921,      5,
       170216, 133473,     74,     93,     12,  70919,   2453,  12942,
       124742,  35677,   8203,  16992, 157354,  15512, 124361, 204583,
          116,    432, 162886,  72125,  50381,    760, 205637,   5782,
       126163, 146021, 143884,   9220, 183394, 181304,    118,   2653,
       157969, 102794, 194655,  12493, 100423,   2223, 237182,  77423,
        37046,  21790, 136063,    823, 193738,    258,    503, 201808,
        40834, 132531,     54,   9674, 103343, 128882,   1294,  27162,
       100901,  28720, 199561,      3,  62219,  25613,     41,    555,
       122522, 107529,   2471, 244521,  34219, 123260, 158899, 143741,
       148949,    483, 172225, 199792,    188,  63888, 155426,   9217,
       187645, 129437,  43570,  73439, 153938, 103885, 205059, 104162,
        48726, 182028, 123540, 147949,  43443, 146508,  27588,  24480,
           45,  21763,  28023,  29368, 108745, 113294, 164928, 224517,
       102652,  62871,  54998,   4390, 122515, 192291,  20100, 180263,
           98,  25669, 154203,  19857,   1917, 244992,    278, 104006,
          215, 176494,  37904,    438,  38453, 124708,  17133,    521,
         9216,  69789,   2397, 171623, 209685,  25554,  15363,  43111,
        17226, 284083,   2243,  34119,   9609,  37380,   2511,  71721,
       166384, 188834, 177736, 140934,  12692,  91536, 164153,  11170,
          699,  25417,  27627,  21241,  27708, 156129,  25292, 160477,
         5404, 161970, 239188,   4098, 167355,   6472,  19237, 163967,
         2921,  22545,   1219, 236457, 127023,  14105,    220, 102680,
        45315,    150, 171131,  13823,  30869, 233867,  43015, 118048,
       205896,  12002, 119890,  20551,  31594, 175914,  92415,   2987,
         2842,    811, 113924, 218603, 170042,  39683, 220308,  42215,
         1198,   2452, 172818,    327, 155703, 115746, 131835, 133038,
          112, 172287,  77130, 127398,  20963,    140,    915,    105,
         7717,  21882, 198773,  97207, 147151,  59959, 233078,  66188,
         2425,   8051, 216132,     47, 199042, 182874, 144733,  13004,
       155821, 286096,   3201,     46,     88,  24181, 244522,   7805,
        53953,    826, 140620,  31627,  46213,   2398, 194594, 138161,
          475, 161417,   1115, 217372,  68425,  63268,  27746, 209778,
        22345,  21348,    891,  83330, 169426, 224037,  31730,  13308,
       171668,   1111,  17329, 197376,  21523,  15818, 209010, 312484,
       156009,     10,   8098, 291457, 160499, 125618,   5716, 169654,
          590, 155362,  33160,  27225,  36946,  40398,  24508, 191189,
        27833, 316554, 185343, 221194, 158600,  92828,  15364, 263918,
       254640,  66362,     71,    394, 199478,  59946, 219513, 146652,
       126042, 180974, 262712,   7854,   1293, 136888, 229853,   1234,
         1345, 155987,   9446,   2952, 191862, 150312,  30380,   2083,
        90137,  11971,  22141, 266524,     51, 141572, 168435,  27173,
         1829,  21050, 117959, 176189,   3699,  12962,    904,   2381,
         2719, 143693, 198994, 127060,  24068, 221107,  12995, 256382,
       285774,   1258,    770, 206718,  93260,   1382, 225694, 138788,
          257,  79828])

In [ ]:
# 목록에 포함된 게임의 데이터만 추출
df = df[df['ID'].isin(ID)]
df

,rating,comment,ID,name
1,10.0,Hands down my favorite new game of BGG CON 200...,30549,Pandemic
2,10.0,I tend to either love or easily tire of co-op ...,30549,Pandemic
4,10.0,This is an amazing co-op game. I play mostly ...,30549,Pandemic
5,10.0,Hey! I can finally rate this game I've been pl...,30549,Pandemic
8,10.0,Love it- great fun with my son. 2 plays so far...,30549,Pandemic
...,...,...,...,...
11185870,2.0,the theme is a turn off - shrimps and crap .....,12962,Reef Encounter
11185871,2.0,There must be a good game in there because so ...,12962,Reef Encounter
11185874,2.0,Played with my gaming group. We're experience...,12962,Reef Encounter
11185875,2.0,"I'm sure that this is a great game. ""Everyone...",12962,Reef Encounter
11185884,1.0,"When I think of what this game is about, I wan...",12962,Reef Encounter

In [ ]:
# 리뷰 길이가 100(평균의 50% 정도) 이상인 데이터 추출
df = df[df['comment'].str.strip().map(len)>=100]
df

,rating,comment,ID,name
1,10.0,Hands down my favorite new game of BGG CON 200...,30549,Pandemic
2,10.0,I tend to either love or easily tire of co-op ...,30549,Pandemic
4,10.0,This is an amazing co-op game. I play mostly ...,30549,Pandemic
5,10.0,Hey! I can finally rate this game I've been pl...,30549,Pandemic
9,10.0,"Fun, fun game. Strategy is required, but defin...",30549,Pandemic
...,...,...,...,...
11185864,2.0,We sold this game last week. Despite having ow...,12962,Reef Encounter
11185868,2.0,Opened the box and read the rules and just can...,12962,Reef Encounter
11185871,2.0,There must be a good game in there because so ...,12962,Reef Encounter
11185874,2.0,Played with my gaming group. We're experience...,12962,Reef Encounter
11185875,2.0,"I'm sure that this is a great game. ""Everyone...",12962,Reef Encounter

In [ ]:
# 인덱스 초기화
df.reset_index(drop=True,inplace=True)

In [ ]:
# 파일 저장
df.to_csv('/content/drive/MyDrive/project4(boardgame_review).csv', index=False)